version: '3.8'

services:
  app:
    build: .
    container_name: d2-rage-counter-app
    restart: unless-stopped
    # FIX: Connect the app to both the internal app-network and the external mysql_network
    networks:
      - app-network
      - mysql_network
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25-alpine
    container_name: d2-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - d2-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: d2-certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    command: renew

networks:
  # This network is for communication between our app and nginx
  d2-network:
    driver: bridge
  # FIX: Define the external network so our app can connect to it
  mysql_network:
    external: true